apiVersion: v1
kind: Pod
metadata:
  name: proyecto_stacknc
spec:
  volumes:
  - name: nextcloud-data
    hostPath:
      path: /root/podman/proyecto/stack_nextcloud/volumes/nextcloud_data
  - name: postgres-data
    hostPath:
      path: /root/podman/proyecto/stack_nextcloud/volumes/postgres_data
  - name: pgadmin-data
    hostPath:
      path: /root/podman/proyecto/stack_nextcloud/volumes/pgadmin_data
  containers:
  - name: nextcloud
    image: docker.io/library/nextcloud:stable-apache
    volumeMounts:
    - mountPath: /var/www/html:z
      name: nextcloud-data
  - name: postgres
    image: postgres:latest
    volumeMounts:
    - mountPath: /var/lib/postgresql/data:z
      name: postgres-data
  - name: pgadmin
    image: dpage/pgadmin4
    env:
    - name: PGADMIN_LISTEN_PORT
      value: "81"
    volumeMounts:
    - mountPath: /var/lib/pgadmin:z
      name: pgadmin-data
